<?php

require_once '/Users/jsf/Documents/workspace/riak-php-client/src/Riak/RiakLinkPhase.php';

/**
 * Test class for RiakLinkPhase.
 * Generated by PHPUnit on 2013-01-29 at 10:12:07.
 */
class RiakLinkPhaseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RiakLinkPhase
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RiakLinkPhase;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers RiakLinkPhase::toArray
     * @todo Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}