<?php

require_once '/Users/jsf/Documents/workspace/riak-php-client/src/Riak/RiakUtils.php';

/**
 * Test class for RiakUtils.
 * Generated by PHPUnit on 2013-01-29 at 10:14:52.
 */
class RiakUtilsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RiakUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RiakUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers RiakUtils::getValue
     * @todo Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RiakUtils::buildRestPath
     * @todo Implement testBuildRestPath().
     */
    public function testBuildRestPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RiakUtils::buildIndexPath
     * @todo Implement testBuildIndexPath().
     */
    public function testBuildIndexPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RiakUtils::httpRequest
     * @todo Implement testHttpRequest().
     */
    public function testHttpRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RiakUtils::parseHttpHeaders
     * @todo Implement testParseHttpHeaders().
     */
    public function testParseHttpHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}